{% raw %}
{% set version = "1.1.0" %}
{% set run_requirements = load_file_regex(
  load_file='envs/conda_run_requirements.txt',
  regex_pattern='.+',
  from_recipe_dir=True).string.strip().split("\n")
  %}
{% set dev_requirements = load_file_regex(
  load_file='envs/conda_dev_requirements.txt',
  regex_pattern='.+',
  from_recipe_dir=True).string.strip().split("\n")
  %}
{% endraw %}
package:
  name: {{ cookiecutter.repo_name }}
  version: {% raw %}{{ version }}{% endraw %}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    {% raw %}
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    {% for req in dev_requirements -%}
      - {{ req }}
    {% endfor %}
    {% endraw %}
  run:
    {% raw %}
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    {% endraw %}

test:
  imports:
    {% raw %}
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    {% for req in dev_requirements -%}
      - {{ req }}
    {% endfor %}
    {% endraw %}

    commands:
      - pytest

about:
  home: https://github.com/{{cookiecutter.github_home}}/{{ cookiecutter.repo_name }}
  license: {{ cookiecutter.open_source_license }}
  description: {{ cookiecutter.description }}
  dev_url: https://github.com/{{cookiecutter.github_home}}/{{ cookiecutter.repo_name }}
  doc_source_url: https://github.com/{{cookiecutter.github_home}}/{{ cookiecutter.repo_name }}/blob/master/README.rst