{% set version = "1.1.0" %}
{% set run_requirements = load_file_regex(
    load_file='envs/conda_run_requirements.txt',
    regex_pattern='.+',
    from_recipe_dir=True).string.strip().split("\n")
%}
{% set dev_requirements = load_file_regex(
    load_file='envs/conda_dev_requirements.txt',
    regex_pattern='.+',
    from_recipe_dir=True).string.strip().split("\n")
%}

package:
  name: {{ cookiecutter.repo_name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    {% for req in dev_requirements -%}
      - {{ req }}
    {% endfor %}
  run:
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}

test:
  imports:
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    {% for req in dev_requirements -%}
      - {{ req }}
    {% endfor %}

    commands:
      - pytest

about:
  home: https://github.com/{{ cookiecutter.project_name }}.github_home }}/{{ cookiecutter.project_name }}.repo_name }}
  license: {{ cookiecutter.open_source_license }}
  description: {{ cookiecutter.description }}
  dev_url: https://github.com/{{cookiecutter.github_home}}}/{{ cookiecutter.project_name }}.repo_name }}
  doc_source_url: https://github.com/{{ cookiecutter.project_name }}.github_home }}/{{ cookiecutter.project_name }}.repo_name }}/blob/master/README.rst