steps:
  - name: Checkout repo
    uses: actions/checkout@v2
  - name: Setup conda
    uses: s-weigand/setup-conda@v1
    run:  conda --version
          which python
  - name: Make environment
  - shell: bash
    run: |
      pip install cookiecutter
      cookiecutter .
      make create_environment
  - name: Test with pytest
    run: pytest test/ --junitxml=test-results.xml
  - name: Upload pytest test results
    uses: actions/upload-artifact@v1
    with:
      name: pytest-results
      path: junit/test-results.xml
  if: ${{ always() }}
  - name: Upload coverage
    shell: bash
    run: coverage report -m