name: Build cookiecutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup conda environment
      uses: goanpeca/setup-miniconda@v1.6.0
    - name: Build env
      run:  |
            conda --version
            pip install --file=requirements.txt
            pytest tests/ --junitxml=test-results.xml --cov=myproj tests/ --cov-report xml:cov.xml
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pytest
        path: |
          '*/test-results.xml'
          '*/cov.xml'
