name: Build cookiecutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup conda environment
      uses: goanpeca/setup-miniconda@v1.6.0
    - name: Build env
    - run:  |
            conda --version
            which python
            conda install cookiecutter
            cookiecutter . project_name=test author_name=D.T description='test run' open_source_license=MIT s3_bucket=TEST aws_profile=default python_version=3.7.0 python_interpreter=python github_home=DanielTemesgen --no-input
            cd test
            make create_environment
            cd ..
            conda install pytest, pytest-cov
            pytest tests/ --junitxml=test-results.xml --cov=myproj tests/ --cov-report xml:cov.xml
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pytest
        path: |
          '*/test-results.xml'
          '*/cov.xml'
