steps:
  - name: Checkout repo
    uses: actions/checkout@v2
  - name: Setup conda
    uses: s-weigand/setup-conda@v1
    run:  conda --version
          which python
  - name: Make environment
  - shell: bash
    run: |
      pip install cookiecutter
      cookiecutter .
      make create_environment
  - name: Test with pytest
    run: pytest test/ --junitxml=test-results.xml
  - name: Job success
    if: ${{ always() }}
      shell: bash
      run: coverage report -m