name: Build cookiecutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup conda environment
      uses: s-weigand/setup-conda@v1
    - run:  conda --version
            which python
            pip install cookiecutter
            pip install pytest
            cookiecutter . project_name=test author_name=D.T description='test run' open_source_license=MIT s3_bucket=TEST aws_profile=default python_version=3.7.0 python_interpreter=python github_home=DanielTemesgen --no-input
            cd test
            make create_environment
    - name: Test with pytest
      run: pytest test/ --junitxml=test-results.xml
    - name: Job success
      if: ${{ always() }}
      shell: bash
      run: coverage report -m